<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Dish;

class DishSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Dish::create(['name' => 'Soep Ling Fa', 'description' => null, 'price' => 3.800, 'dish' => 'Soep']);
        Dish::create(['name' => 'Kippensoep', 'description' => null, 'price' => 2.900, 'dish' => 'Soep']);
        Dish::create(['name' => 'Tomatensoep', 'description' => null, 'price' => 2.900, 'dish' => 'Soep']);
        Dish::create(['name' => 'Haaienvinnensoep', 'description' => null, 'price' => 3.100, 'dish' => 'Soep']);
        Dish::create(['name' => 'Champignonsoep', 'description' => null, 'price' => 3.300, 'dish' => 'Soep']);
        Dish::create(['name' => 'Pekingsoep', 'description' => null, 'price' => 3.800, 'dish' => 'Soep']);
        Dish::create(['name' => 'Wan Tan Soep', 'description' => null, 'price' => 4.300, 'dish' => 'Soep']);
        Dish::create(['name' => 'Chinese Champignonsoep', 'description' => null, 'price' => 4.100, 'dish' => 'Soep']);
        Dish::create(['name' => 'Loempia Ling Fa', 'description' => 'met atjar, ananas en pindasaus', 'price' => 6.200, 'dish' => 'Voorgerecht']);
        Dish::create(['name' => 'Loempia Compleet', 'description' => 'met gesmoord rundvlees en pikante saus', 'price' => 6.200, 'dish' => 'Voorgerecht']);
        Dish::create(['name' => 'Loempia met Kip', 'description' => null, 'price' => 3.900, 'dish' => 'Voorgerecht']);
        Dish::create(['name' => 'Loempia', 'description' => null, 'price' => 3.800, 'dish' => 'Voorgerecht']);
        Dish::create(['name' => 'Chinese mini loempia', 'description' => '4 st.', 'price' => 4.900, 'dish' => 'Voorgerecht']);
        Dish::create(['name' => 'Vegetarische mini loempia', 'description' => '12 st.', 'price' => 4.900, 'dish' => 'Voorgerecht']);
        Dish::create(['name' => 'Kroepoek', 'description' => null, 'price' => 2.500, 'dish' => 'Voorgerecht']);
        Dish::create(['name' => 'Casave Kroepoek', 'description' => null, 'price' => 2.700, 'dish' => 'Voorgerecht']);
        Dish::create(['name' => 'Pangsit Goreng', 'description' => '7 st.', 'price' => 3.900, 'dish' => 'Voorgerecht']);
        Dish::create(['name' => 'Pisang Goreng', 'description' => '5 st.', 'price' => 3.40, 'dish' => 'Voorgerecht']);
        Dish::create(['name' => 'Chinese Dim Sum', 'description' => 'mini loempia, kerry ko, pangsit goreng, garnalenpasteitje', 'price' => 5.40, 'dish' => 'Voorgerecht']);
        Dish::create(['name' => 'Sat&eacute; Babi', 'description' => '4 st.', 'price' => 5.40, 'dish' => 'Voorgerecht']);
        Dish::create(['name' => 'Sat&eacute; Ajam', 'description' => '4 st.', 'price' => 5.40, 'dish' => 'Voorgerecht']);
        Dish::create(['name' => 'Sat&eacute; Garnalen', 'description' => '3 st.', 'price' => 9.900, 'dish' => 'Voorgerecht']);
        Dish::create(['name' => 'Fong Mei Ha', 'description' => 'krokant gepaneerd garnalen. 4 st.', 'price' => 8.100, 'dish' => 'Voorgerecht']);
        Dish::create(['name' => 'Patat', 'description' => null, 'price' => 2.300, 'dish' => 'Voorgerecht']);
        Dish::create(['name' => 'Tsa Siu Mai', 'description' => 'gebakken vleespasteitje. 4 st.', 'price' => 3.500, 'dish' => 'Voorgerecht']);
        Dish::create(['name' => 'Atjar', 'description' => null, 'price' => 3.00, 'dish' => 'Voorgerecht']);
        Dish::create(['name' => 'Witte Rijst', 'description' => null, 'price' => 3.00, 'dish' => 'Voorgerecht']);
        Dish::create(['name' => 'Grote pindasaus', 'description' => null, 'price' => 3.900, 'dish' => 'Voorgerecht']);
        Dish::create(['name' => 'Kleine pindasaus', 'description' => null, 'price' => 2.300, 'dish' => 'Voorgerecht']);
        Dish::create(['name' => 'Kippenpootje', 'description' => null, 'price' => 2.300, 'dish' => 'Voorgerecht']);
        Dish::create(['name' => 'Halve kip', 'description' => null, 'price' => 6.00, 'dish' => 'Voorgerecht']);
        Dish::create(['name' => 'Kroket', 'description' => null, 'price' => 1.40, 'dish' => 'Voorgerecht']);
        Dish::create(['name' => 'Frikandel', 'description' => null, 'price' => 1.40, 'dish' => 'Voorgerecht']);
        Dish::create(['name' => 'Kleine Sambal', 'description' => null, 'price' => 2.500, 'dish' => 'Voorgerecht']);
        Dish::create(['name' => 'Bami of Nasi Goreng Ling Fa', 'description' => 'Foe Yong Hai, Babi Pangang, sat&eacute; en kippenpootje', 'price' => 14.300, 'dish' => 'Bami en Nasi Gerechten']);
        Dish::create(['name' => 'Bami of Nasi Goreng met ei', 'description' => null, 'price' => 5.00, 'dish' => 'Bami en Nasi Gerechten']);
        Dish::create(['name' => 'Bami of Nasi Goreng speciaal', 'description' => null, 'price' => 8.500, 'dish' => 'Bami en Nasi Gerechten']);
        Dish::create(['name' => 'Bami of Nasi Goreng met sat&eacute;', 'description' => '3 st.', 'price' => 8.500, 'dish' => 'Bami en Nasi Gerechten']);
        Dish::create(['name' => 'Nasi Yeung Chow', 'description' => null, 'price' => 10.900, 'dish' => 'Bami en Nasi Gerechten']);
        Dish::create(['name' => 'Nasi Yeung Chow', 'description' => 'met garnaaltjes en Cha Sieuw-vlees', 'price' => 13.00, 'dish' => 'Bami en Nasi Gerechten']);
        Dish::create(['name' => 'Bami of Nasi Malay', 'description' => null, 'price' => 9.300, 'dish' => 'Bami en Nasi Gerechten']);
        Dish::create(['name' => 'Bami of Nasi met kipfilet', 'description' => null, 'price' => 9.300, 'dish' => 'Bami en Nasi Gerechten']);
        Dish::create(['name' => 'Bami of Nasi met varkensvlees', 'description' => null, 'price' => 9.300, 'dish' => 'Bami en Nasi Gerechten']);
        Dish::create(['name' => 'Bami of Nasi met garnalen', 'description' => null, 'price' => 14.300, 'dish' => 'Bami en Nasi Gerechten']);
        Dish::create(['name' => 'Bami of Nasi met ossenhaas', 'description' => null, 'price' => 15.300, 'dish' => 'Bami en Nasi Gerechten']);
        Dish::create(['name' => 'Babi Pangang, Foe Yong Hani en saté', 'description' => null, 'price' => 15.80, 'dish' => 'Combinatie Gerechten (met witte rijst)']);
        Dish::create(['name' => 'Babi Pangang, Tjap Tjoy en saté', 'description' => null, 'price' => 15.80, 'dish' => 'Combinatie Gerechten (met witte rijst)']);
        Dish::create(['name' => 'Babi Pangang, Koe Loe Yuk en saté', 'description' => null, 'price' => 15.80, 'dish' => 'Combinatie Gerechten (met witte rijst)']);
        Dish::create(['name' => 'Babi Pangang, Tau Sie Kai en saté', 'description' => null, 'price' => 16.50, 'dish' => 'Combinatie Gerechten (met witte rijst)']);
        Dish::create(['name' => 'Koe Loe Yuk, Foe Yong Hai en saté', 'description' => null, 'price' => 15.80, 'dish' => 'Combinatie Gerechten (met witte rijst)']);
        Dish::create(['name' => 'Koe Loe Yuk, Tjap Tjoy en saté', 'description' => null, 'price' => 15.80, 'dish' => 'Combinatie Gerechten (met witte rijst)']);
        Dish::create(['name' => 'Foe Yong Hai, Tjap Tjoy en saté', 'description' => null, 'price' => 15.80, 'dish' => 'Combinatie Gerechten (met witte rijst)']);
        Dish::create(['name' => 'Foe Yong Hai, Kip Kerrie en Saté', 'description' => null, 'price' => 16.50, 'dish' => 'Combinatie Gerechten (met witte rijst)']);
        Dish::create(['name' => 'Mihoen Ling Fa', 'description' => 'Foe Yong Hai, Babi Pangang, saté en kippenpootje', 'price' => 16.4, 'dish' => 'Mihoen Gerechten']);
        Dish::create(['name' => 'Mihoen met varkensvlees', 'description' => null, 'price' => 9.300, 'dish' => 'Mihoen Gerechten']);
        Dish::create(['name' => 'Mihoen met kipfilet', 'description' => null, 'price' => 10.40, 'dish' => 'Mihoen Gerechten']);
        Dish::create(['name' => 'Mihoen met ossenhaas', 'description' => null, 'price' => 16.4, 'dish' => 'Mihoen Gerechten']);
        Dish::create(['name' => 'Mihoen met garnalen', 'description' => null, 'price' => 15.30, 'dish' => 'Mihoen Gerechten']);
        Dish::create(['name' => 'Mihoen Singapore-style', 'description' => 'met kleine garnaaltjes en Cha Sieuw-vlees en kerrie poeder', 'price' => 11.90, 'dish' => 'Mihoen Gerechten']);
        Dish::create(['name' => 'Mihoen met Cha Sieuw vlees', 'description' => null, 'price' => 11.20, 'dish' => 'Mihoen Gerechten']);
        Dish::create(['name' => 'Chinese Bami Ling Fa', 'description' => 'Foe Yong Hai, Babi Pangang, saté en kippenpootje', 'price' => 16.90, 'dish' => 'Chinese Bami Gerechten']);
        Dish::create(['name' => 'Chinese Bami met varkensvlees', 'description' => null, 'price' => 10.10, 'dish' => 'Chinese Bami Gerechten']);
        Dish::create(['name' => 'Chinese Bami met kipfilet', 'description' => null, 'price' => 11.20, 'dish' => 'Chinese Bami Gerechten']);
        Dish::create(['name' => 'Chinese Bami met Cha Sieuw-vlees', 'description' => null, 'price' => 12.20, 'dish' => 'Chinese Bami Gerechten']);
        Dish::create(['name' => 'Chinese Bami met garnalen', 'description' => null, 'price' => 15.80, 'dish' => 'Chinese Bami Gerechten']);
        Dish::create(['name' => 'Chinese Bami met ossenhaas', 'description' => null, 'price' => 17.4, 'dish' => 'Chinese Bami Gerechten']);
        Dish::create(['name' => 'Bami of Nasi Rames Ling Fa', 'description' => 'Babi Pangan, Foe Yong Hai, Daging Roedjak, Atjar en kippootje', 'price' => 15.30, 'dish' => 'Indische Gerechten']);
        Dish::create(['name' => 'Bami of Nasi Rames', 'description' => null, 'price' => 8.80, 'dish' => 'Indische Gerechten']);
        Dish::create(['name' => 'Bami of Nasi Rames speciaal', 'description' => null, 'price' => 10.80, 'dish' => 'Indische Gerechten']);
        Dish::create(['name' => 'Gado Gado', 'description' => 'met witte rijst', 'price' => 7.60, 'dish' => 'Indische Gerechten']);
        Dish::create(['name' => 'Daging Smoor', 'description' => 'met witte rijst', 'price' => 13.30, 'dish' => 'Indische Gerechten']);
        Dish::create(['name' => 'Daging Roedjak', 'description' => 'met witte rijst', 'price' => 13.30, 'dish' => 'Indische Gerechten']);
        Dish::create(['name' => 'Foe Yong Hai Ling Fa', 'description' => 'ossenhaas, garnalen en kipfilet', 'price' => 16.4, 'dish' => 'Eiergerechten (met witte rijst)']);
        Dish::create(['name' => 'Foe Yong Hai met varkensvlees', 'description' => null, 'price' => 8.80, 'dish' => 'Eiergerechten (met witte rijst)']);
        Dish::create(['name' => 'Foe Yong Hai met kipfilet', 'description' => null, 'price' => 9.20, 'dish' => 'Eiergerechten (met witte rijst)']);
        Dish::create(['name' => 'Foe Yong Hai met garnalen', 'description' => null, 'price' => 15.30, 'dish' => 'Eiergerechten (met witte rijst)']);
        Dish::create(['name' => 'Foe Yong Hai met krab', 'description' => null, 'price' => 15.30, 'dish' => 'Eiergerechten (met witte rijst)']);
        Dish::create(['name' => 'Foe Yong Hai met Cha Sieuw Vlees', 'description' => null, 'price' => 11.20, 'dish' => 'Eiergerechten (met witte rijst)']);
        Dish::create(['name' => 'Foe Yong Hai met ossenhaas', 'description' => null, 'price' => 16.4, 'dish' => 'Eiergerechten (met witte rijst)']);
        Dish::create(['name' => 'Tjap Tjoy Ling Fa', 'description' => 'ossenhaas, garnalen en kipfilet', 'price' => 16.4, 'dish' => 'Groenten Gerechten (met witte rijst)']);
        Dish::create(['name' => 'Tjap Tjoy met varkensvlees', 'description' => null, 'price' => 8.80, 'dish' => 'Groenten Gerechten (met witte rijst)']);
        Dish::create(['name' => 'Tjap Tjoy met kipfilet', 'description' => null, 'price' => 9.20, 'dish' => 'Groenten Gerechten (met witte rijst)']);
        Dish::create(['name' => 'Tjap Tjoy met ossenhaas', 'description' => null, 'price' => 16.4, 'dish' => 'Groenten Gerechten (met witte rijst)']);
        Dish::create(['name' => 'Tjap Tjoy met garnalen', 'description' => null, 'price' => 15.30, 'dish' => 'Groenten Gerechten (met witte rijst)']);
        Dish::create(['name' => 'Babi Pangang', 'description' => null, 'price' => 12.20, 'dish' => 'Vlees Gerechten (met witte rijst)']);
        Dish::create(['name' => 'Babi Pangang in ketjapsaus', 'description' => null, 'price' => 12.30, 'dish' => 'Vlees Gerechten (met witte rijst)']);
        Dish::create(['name' => 'Cha Sieuw', 'description' => 'rood geroosterd varkensvlees', 'price' => 13.30, 'dish' => 'Vlees Gerechten (met witte rijst)']);
        Dish::create(['name' => 'Cha Sieuw in pikante saus', 'description' => null, 'price' => 13.80, 'dish' => 'Vlees Gerechten (met witte rijst)']);
        Dish::create(['name' => 'Geroosterde speenvarken', 'description' => null, 'price' => 13.80, 'dish' => 'Vlees Gerechten (met witte rijst)']);
        Dish::create(['name' => 'Koe Loe Yuk', 'description' => 'bolletjes vlees met zoetzure saus', 'price' => 11.90, 'dish' => 'Vlees Gerechten (met witte rijst)']);
        Dish::create(['name' => 'Varkenshaas met kerriesaus', 'description' => null, 'price' => 11.90, 'dish' => 'Vlees Gerechten (met witte rijst)']);
        Dish::create(['name' => 'Varkenshaas met ketjapsaus', 'description' => null, 'price' => 11.90, 'dish' => 'Vlees Gerechten (met witte rijst)']);
        Dish::create(['name' => 'Varkenshaas met tomatensaus', 'description' => null, 'price' => 11.90, 'dish' => 'Vlees Gerechten (met witte rijst)']);
        Dish::create(['name' => 'Varkenshaas met champignons in knoflooksaus', 'description' => null, 'price' => 11.90, 'dish' => 'Vlees Gerechten (met witte rijst)']);
        Dish::create(['name' => 'Varkenshaas met Chinese champignons', 'description' => null, 'price' => 12.20, 'dish' => 'Vlees Gerechten (met witte rijst)']);
        Dish::create(['name' => 'Varkenshaas met zwarte bonensaus', 'description' => null, 'price' => 12.20, 'dish' => 'Vlees Gerechten (met witte rijst)']);
        Dish::create(['name' => 'Varkenshaas met verse ananas in zoetzure saus', 'description' => null, 'price' => 13.30, 'dish' => 'Vlees Gerechten (met witte rijst)']);
        Dish::create(['name' => 'Yu Sian Yuk', 'description' => 'varkenshaas met licht zoet pikante kruiden saus', 'price' => 13.30, 'dish' => 'Vlees Gerechten (met witte rijst)']);
        Dish::create(['name' => 'SzeChuan Yuk', 'description' => 'varkenshaas met pittige kruiden saus', 'price' => 13.30, 'dish' => 'Vlees Gerechten (met witte rijst)']);
        Dish::create(['name' => 'Ajam Pangang', 'description' => null, 'price' => 13, 'dish' => 'Kip Gerechten (met witte rijst)']);
        Dish::create(['name' => 'Ajam Pangang in ketjapsaus', 'description' => null, 'price' => 13, 'dish' => 'Kip Gerechten (met witte rijst)']);
        Dish::create(['name' => 'Koe Loe Kai', 'description' => 'bolletjes kip met zoetzure saus', 'price' => 13, 'dish' => 'Kip Gerechten (met witte rijst)']);
        Dish::create(['name' => 'Kipfilet met kerriesaus', 'description' => null, 'price' => 13, 'dish' => 'Kip Gerechten (met witte rijst)']);
        Dish::create(['name' => 'Kipfilet met champignons in knoflooksaus', 'description' => null, 'price' => 13, 'dish' => 'Kip Gerechten (met witte rijst)']);
        Dish::create(['name' => 'Kipfilet met tomatensaus', 'description' => null, 'price' => 13, 'dish' => 'Kip Gerechten (met witte rijst)']);
        Dish::create(['name' => 'Kipfilet met ketjapsaus', 'description' => null, 'price' => 13, 'dish' => 'Kip Gerechten (met witte rijst)']);
        Dish::create(['name' => 'Kipfilet met broccoli in knoflooksaus', 'description' => null, 'price' => 13.30, 'dish' => 'Kip Gerechten (met witte rijst)']);
        Dish::create(['name' => 'Kipfilet met Chinese champignons', 'description' => null, 'price' => 13.30, 'dish' => 'Kip Gerechten (met witte rijst)']);
        Dish::create(['name' => 'Kipfilet met zwarte pepersaus', 'description' => null, 'price' => 13.30, 'dish' => 'Kip Gerechten (met witte rijst)']);
        Dish::create(['name' => 'Kipfilet met verse ananas in zoetzure saus', 'description' => null, 'price' => 13.30, 'dish' => 'Kip Gerechten (met witte rijst)']);
        Dish::create(['name' => 'Tjieuw Yem Kai', 'description' => 'licht gebraden kipfilet met zout en peper', 'price' => 13.30, 'dish' => 'Kip Gerechten (met witte rijst)']);
        Dish::create(['name' => 'Yao Koe Kai', 'description' => 'kipfilet met cashewnoten in licht pikante saus', 'price' => 13.30, 'dish' => 'Kip Gerechten (met witte rijst)']);
        Dish::create(['name' => 'Lychee Kai', 'description' => 'licht gebraden kipfilet met lychee in zoetzure saus', 'price' => 13.80, 'dish' => 'Kip Gerechten (met witte rijst)']);
        Dish::create(['name' => 'Yu Sian Kai', 'description' => 'kipfilet met licht zoet pikante kruidensaus', 'price' => 13.30, 'dish' => 'Kip Gerechten (met witte rijst)']);
        Dish::create(['name' => 'Sze Chuan Kai', 'description' => 'kipfilet met pittige kruidensaus', 'price' => 13.80, 'dish' => 'Kip Gerechten (met witte rijst)']);
        Dish::create(['name' => 'Kung Bao Kai', 'description' => 'kipfilet met cashewnoten in pittige saus', 'price' => 13.80, 'dish' => 'Kip Gerechten (met witte rijst)']);
        Dish::create(['name' => 'Garnalen met champignons in knoflooksaus', 'description' => null, 'price' => 15.90, 'dish' => 'Garnalen Gerechten (met witte rijst)']);
        Dish::create(['name' => 'Garnalen met tomatensaus', 'description' => null, 'price' => 15.90, 'dish' => 'Garnalen Gerechten (met witte rijst)']);
        Dish::create(['name' => 'Garnalen met ketjapsaus', 'description' => null, 'price' => 15.90, 'dish' => 'Garnalen Gerechten (met witte rijst)']);
        Dish::create(['name' => 'Garnalen met broccoli', 'description' => null, 'price' => 16.10, 'dish' => 'Garnalen Gerechten (met witte rijst)']);
        Dish::create(['name' => 'Garnalen met kerriesaus', 'description' => null, 'price' => 16.10, 'dish' => 'Garnalen Gerechten (met witte rijst)']);
        Dish::create(['name' => 'Garnalen met Chinese champignons', 'description' => null, 'price' => 16.10, 'dish' => 'Garnalen Gerechten (met witte rijst)']);
        Dish::create(['name' => 'Garnalen met zwarte pepersaus', 'description' => null, 'price' => 16.10, 'dish' => 'Garnalen Gerechten (met witte rijst)']);
        Dish::create(['name' => 'Garnalen met chilisaus', 'description' => null, 'price' => 16.10, 'dish' => 'Garnalen Gerechten (met witte rijst)']);
        Dish::create(['name' => 'Yu Sian Haa', 'description' => 'garnalen met licht zoet pikante kruidensaus', 'price' => 16.10, 'dish' => 'Garnalen Gerechten (met witte rijst)']);
        Dish::create(['name' => 'Tjieuw Yem Haa', 'description' => 'licht gebraden garnalen met zout en peper', 'price' => 16.10, 'dish' => 'Garnalen Gerechten (met witte rijst)']);
        Dish::create(['name' => 'Tja Tai Haa', 'description' => 'krokant gebakken garnalen', 'price' => 16.10, 'dish' => 'Garnalen Gerechten (met witte rijst)']);
        Dish::create(['name' => 'Sze Chuan Haa', 'description' => null, 'price' => 16.4, 'dish' => 'Garnalen Gerechten (met witte rijst)']);
        Dish::create(['name' => 'Ossenhaas met chanpignons in knoflooksaus', 'description' => null, 'price' => 16.90, 'dish' => 'Ossenhaas Gerechten (met witte rijst)']);
        Dish::create(['name' => 'Ossenhaas met tomatensaus', 'description' => null, 'price' => 16.90, 'dish' => 'Ossenhaas Gerechten (met witte rijst)']);
        Dish::create(['name' => 'Ossenhaas met ketjapsaus', 'description' => null, 'price' => 16.90, 'dish' => 'Ossenhaas Gerechten (met witte rijst)']);
        Dish::create(['name' => 'Ossenhaas met broccoli', 'description' => null, 'price' => 17.10, 'dish' => 'Ossenhaas Gerechten (met witte rijst)']);
        Dish::create(['name' => 'Ossenhaas met Chinese champignons', 'description' => null, 'price' => 17.10, 'dish' => 'Ossenhaas Gerechten (met witte rijst)']);
        Dish::create(['name' => 'Ossenhaas met kerriesaus', 'description' => null, 'price' => 17.10, 'dish' => 'Ossenhaas Gerechten (met witte rijst)']);
        Dish::create(['name' => 'Ossenhaas met zwarte bonensaus', 'description' => null, 'price' => 17.10, 'dish' => 'Ossenhaas Gerechten (met witte rijst)']);
        Dish::create(['name' => 'Ossenhaas met zwarte pepersaus', 'description' => null, 'price' => 17.10, 'dish' => 'Ossenhaas Gerechten (met witte rijst)']);
        Dish::create(['name' => 'Yu Sian Ngau Yuk', 'description' => 'ossenhaas met licht zoet pikante kruidensaus', 'price' => 17.10, 'dish' => 'Ossenhaas Gerechten (met witte rijst)']);
        Dish::create(['name' => 'Sze Chuan Ngau Yuk', 'description' => 'ossenhaas met pittige kruidensaus', 'price' => 17.4, 'dish' => 'Ossenhaas Gerechten (met witte rijst)']);
        Dish::create(['name' => 'Visfilet met kerriesaus', 'description' => null, 'price' => 14.50, 'dish' => 'Vissen Gerechten (met witte rijst)']);
        Dish::create(['name' => 'Visfilet met oestersaus', 'description' => null, 'price' => 14.50, 'dish' => 'Vissen Gerechten (met witte rijst)']);
        Dish::create(['name' => 'Visfilet met zoetzure saus', 'description' => 'licht gebraden visfilet in zoete pikante saus', 'price' => 14.50, 'dish' => 'Vissen Gerechten (met witte rijst)']);
        Dish::create(['name' => 'Hong Shau Yu', 'description' => 'licht gebraden visfilet in zoete pikante saus', 'price' => 14.50, 'dish' => 'Vissen Gerechten (met witte rijst)']);
        Dish::create(['name' => 'Tjeuw Yem Yu', 'description' => 'licht gebraden visfilet met zout en peper', 'price' => 15, 'dish' => 'Vissen Gerechten (met witte rijst)']);
        Dish::create(['name' => 'San Sching Po', 'description' => 'visfilet, garnalen, krab en groenten in knoflooksaus', 'price' => 16.10, 'dish' => 'Vissen Gerechten (met witte rijst)']);
        Dish::create(['name' => 'Geroosterde Peking Eend', 'description' => null, 'price' => 16.60, 'dish' => 'Peking Eend (met witte rijst)']);
        Dish::create(['name' => 'Peking Eend met verse ananas in zoetzure saus', 'description' => null, 'price' => 17.10, 'dish' => 'Peking Eend (met witte rijst)']);
        Dish::create(['name' => 'Peking Eend met Chinese champignons in oestersaus', 'description' => null, 'price' => 17.10, 'dish' => 'Peking Eend (met witte rijst)']);
        Dish::create(['name' => 'Yu Sian Ya', 'description' => 'peking eend met licht zoet pikante kruidensaus', 'price' => 17.10, 'dish' => 'Peking Eend (met witte rijst)']);
        Dish::create(['name' => 'Tiepan Ling Fa', 'description' => 'garnalen, kipfilet, ossenhaas en groenten in zwarte pepersaus', 'price' => 17.90, 'dish' => 'Tiepan Specialiteiten (met witte rijst)']);
        Dish::create(['name' => 'Tiepan Kai', 'description' => 'licht gebraden kipfilet en groenten met zoet pikante saus', 'price' => 15.30, 'dish' => 'Tiepan Specialiteiten (met witte rijst)']);
        Dish::create(['name' => 'Tiepan San Yuk', 'description' => 'lichtgrbaden varkenshaas, kipfilet, ossenhaas en groenten met zoet pikante saus', 'price' => 17.10, 'dish' => 'Tiepan Specialiteiten (met witte rijst)']);
        Dish::create(['name' => 'Tiepan Haa', 'description' => 'garnalen en groenten met zoet pikante saus', 'price' => 17.4, 'dish' => 'Tiepan Specialiteiten (met witte rijst)']);
        Dish::create(['name' => 'Tiepan Ngau Yuk', 'description' => '5st. ossenhaas en groenten met zoet pikante saus', 'price' => 19.50, 'dish' => 'Tiepan Specialiteiten (met witte rijst)']);
        Dish::create(['name' => 'Tau Fu Po', 'description' => 'sojakaas, cha sieuw garnalen en chinese paddenstoelen', 'price' => 15.30, 'dish' => 'Tiepan Specialiteiten (met witte rijst)']);
        Dish::create(['name' => 'Vegetarische Tjap Tjoy', 'description' => null, 'price' => 8.30, 'dish' => 'Vegetarische gerechten (met witte rijst)']);
        Dish::create(['name' => 'Lo Han Zhai', 'description' => 'sojakaas, Chinese paddenstoelen en groenten in knoflooksaus', 'price' => 11.20, 'dish' => 'Vegetarische gerechten (met witte rijst)']);
        Dish::create(['name' => 'Vegetarische Foe Yong Hai', 'description' => null, 'price' => 8.30, 'dish' => 'Vegetarische gerechten (met witte rijst)']);
        Dish::create(['name' => 'Frites, saté (2st.) en ei', 'description' => null, 'price' => 6.50, 'dish' => 'Kindermenu']);
        Dish::create(['name' => 'Frites, kippootje en ei', 'description' => null, 'price' => 6.50, 'dish' => 'Kindermenu']);
        Dish::create(['name' => 'Frites, mini loempia (2st.) en ei', 'description' => null, 'price' => 6.50, 'dish' => 'Kindermenu']);
        Dish::create(['name' => 'Kinder Bami of Nasi met saté (2st.) en ei', 'description' => null, 'price' => 6.50, 'dish' => 'Kindermenu']);
        Dish::create(['name' => 'Indische rijsttafel (voor 1 persoon)', 'description' => 'Gado gado, Foe Yong Hai, saté, Daging Roedjak, Daging Smoor, Ajam Ketjap, Atjar, Pisang Goreng, Pindas en Cocos', 'price' => 16.4, 'dish' => 'Rijsttafels']);
        Dish::create(['name' => 'Indische rijsttafel vanaf 2 personen... Per persoon', 'description' => 'Ajam Ketjap, Gado Gado, Daging Smoor, Kroepoek, Daging Roedjak, Foe Yong Hai, Saté, Sambal Goreng Boontjes, Sambal Goreng Kering, Atjar, Pisang Goreng, Pinda en Cocos', 'price' => 15, 'dish' => 'Rijsttafels']);
        Dish::create(['name' => 'Chinese Indische Rijsttafel vanaf 4 personen... per persoon', 'description' => 'Foe Yong Hai, Babi Pangang, Tjap Tjoy, Koe Loe Yuk, Ajam Ketjap, Daging Smoor, Daging Roedjak, Saté, Ei, Kroepoek, Sambal Goeren boontjes, Atjar, Pisang Goreng, Pinda en Cocos', 'price' => 16.50, 'dish' => 'Rijsttafels']);
        Dish::create(['name' => 'Chinese Rijsttafel vanaf 2 personen... per persoon', 'description' => 'Kippen- of Tomatensoep, Tjap Tjoy met kipfilet, Koe Loe Yuk, Gebakken garnalen, Babi Pangang, Foe Yong Hai, saté, kroepoek', 'price' => 17, 'dish' => 'Rijsttafels']);
        Dish::create(['name' => 'Kantones Rijsttafel vanaf 2 personen... per persoon', 'description' => 'Wan Tan soep, Chinese Dim Sum (mini loempia, kerrie ko, pangsit goreng, garnalen, pasteitje), Geroosterde Peking Eend, Lychee Kai (licht gebraden kipfilet met lychee in zoetzure saus), Tau Sie Haa (garnalen met zwarte bonensaus)', 'price' => 23, 'dish' => 'Rijsttafels']);
        Dish::create(['name' => 'Sze Chuan Rijsttafel vanaf 2 personen... per persoon', 'description' => 'Peking Soep (pittige lichtzure soep), Chinese Dim Sum (mini loempia, kerrie ko, pangsit goreng, garnalen, pastei(tje), Tjieuw Yem Kai (licht gebakken kipfilet met zout en peper), Lychee Yuk (licht gebraden varkensvlees met lychee in zoetzure saus), Yu Sian Ngau Yuk (ossenhaas met licht zoet pikante kruiden saus)', 'price' => 23, 'dish' => 'Rijsttafels']);
        Dish::create(['name' => 'Buffet Menu A, per persoon', 'description' => 'Mini Loempia\'s, Pisang Goreng, Babi Pangang, Koe Loe Yuk, Foe Yong Hai, Kipfilet met zwarte bonensaus, Tjap Tjoy met kipfilet, saté Ajam', 'price' => 12.80, 'dish' => 'Buffet']);
        Dish::create(['name' => 'Buffet Menu B, per persoon', 'description' => 'Mini Loempia\'s, Pisang Goreng, Babi Pangang, Foe Yong Hai, Kung Bao Kai, Hong Shau Yu, saté Ajam, Ossenhaas met zwarte bonensaus, Kipfilet met kerriesaus', 'price' => 15, 'dish' => 'Buffet']);
        Dish::create(['name' => 'Bami of Nasi Goreng ipv rijst', 'description' => null, 'price' => 0.90, 'dish' => 'Diversen']);
        Dish::create(['name' => 'Mihoen Goreng ipv rijst', 'description' => null, 'price' => 2.50, 'dish' => 'Diversen']);
        Dish::create(['name' => 'Chinese Bami ipv rijst', 'description' => null, 'price' => 2.50, 'dish' => 'Diversen']);
        

    }
}
